name = "projsite"
compatibility_date = "2024-12-27"
compatibility_flags = [ "nodejs_compat" ]


[workers_dev]
log_level = "debug"

# Workers Logs configuration
[logs]
enabled = true
sampling_rate = 1.0  # 100% sampling rate

# [vars]
# MY_VAR = "my-variable"
# TODO:: add the pasword as secret somehow?? NOT SAFE LIKE THIS!!
DATABASE_URL="postgresql://projsite_db_owner:JUoRji0n8KzW@ep-tight-sound-a2sympt8-pooler.eu-central-1.aws.neon.tech/projsite_db?sslmode=require"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"