name = "projsite-mongo"
compatibility_date = "2024-12-18"
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true
invocation_logs = false

# Run: wrangler secret put MONGODB_URI
# Run: wrangler secret put CLERK_SECRET_KEY
# Run: wrangler secret put SERVICE_API_KEY 


[alias]

