name = "projsite"
compatibility_date = "2024-12-27"
compatibility_flags = [ "nodejs_compat" ]

[observability.logs]
enabled = true

invocation_logs = false

[vars]
CLERK_PUBLISHABLE_KEY = "pk_test_cmlnaHQtcGFyYWtlZXQtNjAuY2xlcmsuYWNjb3VudHMuZGV2JA"

# Run: wrangler secret put DATABASE_URL
# Run: wrangler secret put CLERK_SECRET_KEY
# Run: wrangler secret put SERVICE_API_KEY

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"